name:                sonic
version:             0.2.0
github:              "adjoint-io/sonic"
license:             MIT
maintainer:          "Adjoint Inc (info@adjoint.io)"
category:            Cryptography

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/adjoint-io/sonic#readme>

dependencies:
- base
- galois-field
- elliptic-curve
- pairing
- protolude
- bulletproofs
- polynomial
- MonadRandom

default-extensions:
  - LambdaCase
  - RecordWildCards
  - OverloadedStrings
  - NoImplicitPrelude
  - FlexibleInstances
  - FlexibleContexts
  - ScopedTypeVariables
  - RankNTypes

ghc-options:
  -Wall
  -Werror
  -Wcompat
  -Wincomplete-record-updates
  -Wredundant-constraints
  -Wno-unused-matches
  -Wno-name-shadowing
  -Wno-type-defaults
  -Wno-orphans
  -Wno-incomplete-uni-patterns
  -Wno-incomplete-patterns

library:
  source-dirs: src
  exposed-modules:
  - Sonic.CommitmentScheme
  - Sonic.Constraints
  - Sonic.Protocol
  - Sonic.SRS
  - Sonic.Signature
  - Sonic.Utils

executables:
  sonic-example:
    main: Main.hs
    source-dirs:
      - examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sonic
    - tasty
    - tasty-discover
    - tasty-hunit
    - tasty-quickcheck
    - QuickCheck
tests:
  sonic-test:
    main: Test.Main.hs
    source-dirs: test
    dependencies:
      - sonic
      - QuickCheck
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-quickcheck

benchmarks:
  sonic-benchmarks:
    source-dirs:
      - bench
      - test
    main: Main.hs
    dependencies:
      - sonic
      - criterion
      - QuickCheck
      - tasty
      - tasty-quickcheck
      - tasty-hunit
    other-modules:
      - Test.Reference
