name:        sonic
version:     0.3.0
synopsis:    Sonic
description: Please see the README on GitHub at <https://github.com/adjoint-io/sonic#readme>
maintainer:  Adjoint Inc (info@adjoint.io)
license:     MIT
github:      adjoint-io/sonic
category:    Cryptography

dependencies:
  - base >= 4.7 && < 5
  - protolude
  - bulletproofs
  - elliptic-curve >= 0.3
  - galois-field >= 1.0
  - MonadRandom
  - pairing
  - poly
  - semirings
  - vector

default-extensions:
  - LambdaCase
  - RecordWildCards
  - OverloadedStrings
  - NoImplicitPrelude
  - FlexibleInstances
  - FlexibleContexts
  - ScopedTypeVariables
  - RankNTypes

extra-source-files:
  - README.md
  - ChangeLog.md

ghc-options:
  -Wall
  -Werror
  -Wcompat
  -Wincomplete-record-updates
  -Wredundant-constraints
  -Wno-unused-matches
  -Wno-name-shadowing
  -Wno-type-defaults
  -Wno-orphans
  -Wno-incomplete-uni-patterns
  -Wno-incomplete-patterns

library:
  exposed-modules:
    - Sonic.CommitmentScheme
    - Sonic.Constraints
    - Sonic.Protocol
    - Sonic.SRS
    - Sonic.Signature
    - Sonic.Utils
  source-dirs:
    - src

tests:
  sonic-test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - sonic
      - QuickCheck
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-quickcheck

benchmarks:
  sonic-benchmarks:
    source-dirs:
      - bench
      - test
    main: Main.hs
    dependencies:
      - sonic
      - criterion
      - QuickCheck
      - tasty
      - tasty-quickcheck
      - tasty-hunit
    other-modules:
      - Test.Reference

executables:
  sonic-example:
    main: Main
    dependencies:
      - sonic
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-quickcheck
      - QuickCheck
    ghc-options:
      -threaded
      -rtsopts
      -with-rtsopts=-N
    source-dirs:
      - examples
