resolver: lts-13.23
packages:
  - .
extra-deps:
  - git: https://github.com/adjoint-io/poly.git
    commit: b75b853025ea75ba64f62f39d4524832f0117e36
  - elliptic-curve-0.3.0
  - galois-field-1.0.0
  - pairing-1.0.0
  - semirings-0.5.1
  - bulletproofs-1.1.0
