resolver: lts-13.23

packages:
  - .

extra-deps:
  - bulletproofs-1.0.1
  - galois-field-0.4.0
  - poly-0.3.1.0
  - semirings-0.4.2
  - pairing-0.5.0
  - elliptic-curve-0.2.2
  - git: https://github.com/adjoint-io/polynomial.git
    commit: 7478e09d90f5d256d1afca49eda166a199f54cac
