resolver: lts-13.23

packages:
- .

extra-deps:
  - git: https://github.com/adjoint-io/polynomial.git
    commit: 7478e09d90f5d256d1afca49eda166a199f54cac
  - git: https://github.com/adjoint-io/bulletproofs.git
    commit: 08069fa77ebf76bd5133b5c8a1b607d440acaa13
  - git: git@github.com:adjoint-io/galois-field.git
    commit: 30665fdc2af450e2d519c81bca91d85c63057b6d
  - git: git@github.com:adjoint-io/pairing.git
    commit: 9d2fa6c59dbd975d6bf1cf762b5d33b58ddbd612
